spring:
  profiles: 
    active: local

server:
  port: 19080
  servlet:
    context-path: /zuul-server

logging:
  level:
    root: INFO
    com.psys.hobb: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
            mvc.method.annotation.ServletInvocableHandleMethod: TRACE
            