eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18080/eureka-server/eureka/

spring:
  application:
    name: zuul-server

zuul:
  routes:
    api-sec:
      path: /api-sec/**
      serviceId: sec-server
  add-proxy-headers: true

auth-server: http://localhost:18090/auth-server
security:
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: app
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
      user-info-uri: ${auth-server}/auth-server/user
      prefer-token-info: false